[package]
name = "q5skeyboard"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "q5skeyboard"
path = "src/main/rust/main.rs"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
